# Generated by Django 4.1.2 on 2022-11-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
