# Generated by Django 4.1.2 on 2022-11-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='duration',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
