# Generated by Django 4.1.2 on 2022-11-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
